name: dekiの屋
description: 吧啦吧啦

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: "https://deki1516.github.io/"
google_analytics: ""
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "deki1516"

# Disqus config
disqus-shortname: ""

# Markdown Processors
kramdown:
  auto_ids          : true
  entity_output     : as_char
  toc_levels        : [1, 2, 3, 4, 5, 6]
  smart_quotes      : lsquo,rsquo,ldquo,rdquo
  input             : GFM
  hard_wrap         : false
  footnote_nr       : 1
  show_warnings     : false
